# Generated by Django 6.0.3 on 2026-04-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('landlord', 'Landlord Dispute'), ('shopping', 'Online Shopping Fraud'), ('salary', 'Salary & PF Issue'), ('bank', 'Bank & Finance'), ('medical', 'Medical Negligence'), ('telecom', 'Telecom Dispute'), ('service', 'Service Fraud'), ('product', 'Product Defect'), ('other', 'Other')], default='other', max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('laws_violated', models.JSONField(blank=True, null=True)),
                ('forum_type', models.CharField(blank=True, max_length=200)),
                ('forum_address', models.TextField(blank=True)),
                ('documents_needed', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('notice_sent', 'Notice Sent'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notice_sent', models.BooleanField(default=False)),
                ('is_analysed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.case')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_text', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='cases.case')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
