# Generated by Django 6.0.3 on 2026-04-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='respondent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
